import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os

CYBERCRIME_EMAIL = "report@cybercrime.gov.in"  # demo target


def send_scam_report(session_id, message, upi, phone, timestamp):
    sender_email = os.getenv("REPORT_EMAIL")
    sender_password = os.getenv("REPORT_EMAIL_PASSWORD")
    
    print("Sender:", sender_email)
    print("Password loaded:", bool(sender_password))

    subject = f"Scam Report - Session {session_id}"

    body = f"""
    🚨 Scam Interaction Detected

    Session ID: {session_id}
    Timestamp: {timestamp}

    Message:
    {message}

    Extracted Intelligence:
    UPI ID: {upi}
    Phone: {phone}

    Generated by AI Scam Honeypot System
    """

    msg = MIMEMultipart()
    msg["From"] = sender_email
    msg["To"] = CYBERCRIME_EMAIL
    msg["Subject"] = subject

    msg.attach(MIMEText(body, "plain"))

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()
        print("✅ Scam report email sent")

    except Exception as e:
        print("❌ Email failed:", e)